apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pact-broker
  namespace: pact-broker-prod
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "pact-broker-pact-broker-prod-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
  - hosts:
    - pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: pact-broker
            port:
              number: 80
